### ISSUE TITLE
HUD Redesign

### ISSUE THREAD

**Issue by ACupOfCoftea** [Jjman739/STAB#12]
Redesign the HUD to have the health and energy be arranged to look like the S.T.A.B logo.

Edit by @Jjman739 to add tasks:
- [x] Design a good-looking sprite/color scheme for the HP
- [ ] Create scrap and metal icons
- [ ] Edit the in-game UI to use the new designs

**Comment by Jjman739** [comment]
![image](https://github.com/user-attachments/assets/fd8d8df1-2dbc-4309-bc33-4dbd9e1c129e)
A sketch of how it should function. Will need some art direction to make it look good though.

**Comment by Jjman739** [comment]
![image](https://github.com/user-attachments/assets/c8b4d0cb-7132-4150-97fe-f6b90c8fb640)
Let's use this design by Jooby instead. I like how sleek it is. Tasks otherwise unchanged.
